# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "commander-5.1.0" = {
      name = "commander";
      packageName = "commander";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-5.1.0.tgz";
        sha512 = "P0CysNDQ7rtVw4QIQtm+MRxV66vKFSvlsQvGYXZWR3qFU0jlMKHZZZgw8e+8DSah4UDKMqnknRDQz+xuQXQ/Zg==";
      };
    };
    "denque-1.5.1" = {
      name = "denque";
      packageName = "denque";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/denque/-/denque-1.5.1.tgz";
        sha512 = "XwE+iZ4D6ZUB7mfYRMb5wByE8L74HCn30FBN7sWnXksWc1LO1bPDl67pBR9o/kC4z/xSNAwkMYcGgqDV3BE3Hw==";
      };
    };
    "jsonc-parser-2.3.1" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-2.3.1.tgz";
        sha512 = "H8jvkz1O50L3dMZCsLqiuB2tA7muqbSg1AtGEkN0leAqGjsUzDJir3Zwr02BhqdcITPg3ei3mZ+HjMocAknhhg==";
      };
    };
    "ts-set-utils-0.2.0" = {
      name = "ts-set-utils";
      packageName = "ts-set-utils";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-set-utils/-/ts-set-utils-0.2.0.tgz";
        sha512 = "+4X9p1qqaSmENkuWrqgTet199mqwnAZKdGVNUQejldZGZUDzmtjMaQ+EvA9l1EHl2j/31RYRONc8yJbbWF1QTg==";
      };
    };
    "vscode-jsonrpc-8.1.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.1.0.tgz";
        sha512 = "6TDy/abTQk+zDGYazgbIPc+4JoXdwC8NHU9Pbn4UJP1fehUyZmM4RHp5IthX7A6L5KS30PRui+j+tbbMMMafdw==";
      };
    };
    "vscode-languageserver-6.1.1" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "6.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-6.1.1.tgz";
        sha512 = "DueEpkUAkD5XTR4MLYNr6bQIp/UFR0/IPApgXU3YfCBCB08u2sm9hRCs6DxYZELkk++STPjpcjksR2H8qI3cDQ==";
      };
    };
    "vscode-languageserver-protocol-3.17.3" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.3.tgz";
        sha512 = "924/h0AqsMtA5yK22GgMtCYiMdCOtWTSGgUOkgEDX+wk2b0x4sAfLiO4NxBxqbiVtz7K7/1/RgVrVI0NClZwqA==";
      };
    };
    "vscode-languageserver-textdocument-1.0.9" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.9.tgz";
        sha512 = "NPfHVGFW2/fQEWHspr8x3PXhRgtFbuDZdl7p6ifuN3M7nk2Yjf5POr/NfDBuAiQG88DehDyJ7nGOT+p+edEtbw==";
      };
    };
    "vscode-languageserver-types-3.17.3" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.3.tgz";
        sha512 = "SYU4z1dL0PyIMd4Vj8YOqFvHu7Hz/enbWtpfnVbJHU4Nd1YNYx8u0ennumc6h48GQNeOLxmwySmnADouT/AuZA==";
      };
    };
    "vscode-uri-2.1.2" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-2.1.2.tgz";
        sha512 = "8TEXQxlldWAuIODdukIb+TR5s+9Ds40eSJrw+1iDDA9IFORPjMELarNQE3myz5XIkWWpdprmJjm1/SxMlWOC8A==";
      };
    };
  };
in
{
  kos-language-server = nodeEnv.buildNodePackage {
    name = "kos-language-server";
    packageName = "kos-language-server";
    version = "1.1.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/kos-language-server/-/kos-language-server-1.1.5.tgz";
      sha512 = "Jxo6w8sI7IlS89Mzowdt7MFGABrhpaPFnGuI7wVo9QxnKdYzEnxPXOXLPr2fErqBAcvUVRk8IzB+g5sE+A6N/g==";
    };
    dependencies = [
      sources."commander-5.1.0"
      sources."denque-1.5.1"
      sources."jsonc-parser-2.3.1"
      sources."ts-set-utils-0.2.0"
      sources."vscode-jsonrpc-8.1.0"
      sources."vscode-languageserver-6.1.1"
      sources."vscode-languageserver-protocol-3.17.3"
      sources."vscode-languageserver-textdocument-1.0.9"
      sources."vscode-languageserver-types-3.17.3"
      sources."vscode-uri-2.1.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A Language server for Kerbal Operating System. A mod for Kerbal Space Program.";
      homepage = "https://github.com/jonnyboyC/kos-language-server#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
